# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :beta do
    enable_automatic_code_signing
    increment_build_number
    build_ios_app(
      configuration: "Debug",
      scheme: "SayHello",
      clean: true,
      export_method: "development",
      output_name: "SayHello.ipa"
    )
    crashlytics(
      api_token: "API_TOKEN",
      build_secret: "SECRET_KEY",
      groups: "DemoApp",
      notes: "Automatic iOS Build"
    )
  end
end
